//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtiranHelpEntities : DbContext
    {
        public AtiranHelpEntities()
            : base("name=AtiranHelpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answers> Answers { get; set; }
        public virtual DbSet<overal_setting> overal_setting { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<UsePermition> UsePermition { get; set; }
        public virtual DbSet<UsersManagement> UsersManagement { get; set; }
    }
}
