//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsePermition
    {
        public int id { get; set; }
        public int permitionId { get; set; }
    
        public virtual UsersManagement UsersManagement { get; set; }
    }
}
